import { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Recommendations from "../components/Recommendations";
import Error from "../components/Error";

export default function Home() {
  const [animeRecommendation, setAnimeRecommendation] = useState([]);
  const [isError, setIsError] = useState(false);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const animeRecommendationFetch = await fetch(
          "https://api.jikan.moe/v4/recommendations/anime"
        );
        const jsonAnimeRecommendation = await animeRecommendationFetch.json();
        setAnimeRecommendation(jsonAnimeRecommendation.data);
      } catch (error) {
        setIsError(true);
      }
    };

    fetchData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Anime Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header></Header> */}
      {/* <Error></Error> */}
      {isError ? (
        <Error></Error>
      ) : (
        <Recommendations
          recommendations={animeRecommendation}
        ></Recommendations>
      )}
    </div>
  );
}
