import { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Body from "../components/Body";
import Header from "../components/Header";

export default function Home() {
  const [topAnimes, setTopAnimes] = useState([]);
  const [animeRecommendation, setAnimeRecommendation] = useState([]);

  useEffect(() => {
    const fetchData = async () => {
      const topAnimeFetch = await fetch("https://api.jikan.moe/v4/top/anime");
      const animeRecommendationFetch = await fetch(
        "https://api.jikan.moe/v4/recommendations/anime"
      );
      const jsonTopAnimes = await topAnimeFetch.json();
      const jsonAnimeRecommendation = await animeRecommendationFetch.json();
      setTopAnimes(jsonTopAnimes.data);
      setAnimeRecommendation(jsonAnimeRecommendation.data);
    };

    fetchData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header className={styles.header}></Header>
      <Body recommendations={animeRecommendation} top={topAnimes}></Body>
    </div>
  );
}
